### PR TITLE
Use variable to set ClamdScan Defaults 

### LINKED ISSUE #1: Issue: Clamd conf settings should match Docker-Compose
Clamd defaults should be updated to match the docker-compose defaults. 

https://github.com/artefactual-labs/ansible-clamav/blob/master/templates/etc/clamd.d/scan.conf.j2

In part for consistency but also, currently, the MaxStreamLength is set too small at 10MB. 

Docker compose defaults are here: https://github.com/artefactual-labs/am/blob/stable/1.7.x/compose/.env 

* `clamd_MaxScanSize: "150M"` in defaults/main.yml
* `MAxScanSize={{ clamd_MaxScanSize }}`

Example configuration variables default file for our Elasticsearch deployment: https://github.com/artefactual-labs/ansible-elasticsearch/blob/master/defaults/main.yml 

Update: Config should appear in each environment - currently not in Ubuntu

Ubuntu: https://github.com/artefactual-labs/ansible-clamav/blob/master/tasks/ubuntu.yml
RedHat: https://github.com/artefactual-labs/ansible-clamav/blob/master/tasks/redhat.yml#L45

### PR DESCRIPTION
**Pull request by scollazo**
Closes #1

### CODE REVIEW

**Comment by ross-spencer** [comment]
Have modified the original PR to match defaults and variable names used on the af-labs docker-compose 1.7.x branch https://github.com/artefactual-labs/am/blob/stable/1.7.x/compose/.env cc. @scollazo

**Review by hakamine — APPROVED** [review]
👍 Looks good. Thank you for fixing the issue.

**Review by scollazo — COMMENTED** [review]
LGTM!

**Comment by scollazo** [comment]
After more close review, seems like /etc/clamav/clamd.conf is not configured in ubuntu, only in redhat systems?

**Comment by hakamine** [comment]
Hmmm, @scollazo is correct.... some additional fixes are needed to make it work in ubuntu.

**Comment by ross-spencer** [comment]
Replaced by https://github.com/artefactual-labs/ansible-clamav/pull/3

**Pull request closed without merging**
